apiVersion: v1
kind: Pod
metadata:
  name: pod-with-labels
  labels:
    env: qa
    tier: frontend
spec:
  containers:
  - name: nginx-app
    image: nginx:1.12-alpine
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
